"""add_two_factor_backup_codes

Revision ID: 1daab6385435
Revises: c280720c9c41
Create Date: 2025-11-24 21:58:13.890725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1daab6385435'
down_revision: Union[str, Sequence[str], None] = 'c280720c9c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_backup_codes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_backup_codes')
    # ### end Alembic commands ###
