"""add_theme_model

Revision ID: 22ef6997daa0
Revises: 7b84c92e8d55
Create Date: 2025-11-24 21:44:07.657418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ef6997daa0'
down_revision: Union[str, Sequence[str], None] = '7b84c92e8d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system_theme', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('typography', sa.JSON(), nullable=True),
    sa.Column('spacing', sa.JSON(), nullable=True),
    sa.Column('borderRadius', sa.JSON(), nullable=True),
    sa.Column('shadows', sa.JSON(), nullable=True),
    sa.Column('custom_properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_theme_org_active', 'themes', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    op.create_index(op.f('ix_themes_organization_id'), 'themes', ['organization_id'], unique=False)
    op.create_index('uix_theme_org_name', 'themes', ['organization_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_theme_org_name', table_name='themes')
    op.drop_index(op.f('ix_themes_organization_id'), table_name='themes')
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_index('ix_theme_org_active', table_name='themes')
    op.drop_table('themes')
    # ### end Alembic commands ###
