"""add_content_schedule_table

Revision ID: 3a3ceb7b647d
Revises: 6a494df61c26
Create Date: 2025-11-24 20:48:09.407828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3ceb7b647d'
down_revision: Union[str, Sequence[str], None] = '6a494df61c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_entry_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False, comment="Action to perform: 'publish' or 'unpublish'"),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False, comment='When to execute the action'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending, completed, failed, cancelled'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_entry_id'], ['content_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_schedules_content_entry_id'), 'content_schedules', ['content_entry_id'], unique=False)
    op.create_index(op.f('ix_content_schedules_id'), 'content_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_content_schedules_organization_id'), 'content_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_content_schedules_scheduled_at'), 'content_schedules', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_content_schedules_status'), 'content_schedules', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_schedules_status'), table_name='content_schedules')
    op.drop_index(op.f('ix_content_schedules_scheduled_at'), table_name='content_schedules')
    op.drop_index(op.f('ix_content_schedules_organization_id'), table_name='content_schedules')
    op.drop_index(op.f('ix_content_schedules_id'), table_name='content_schedules')
    op.drop_index(op.f('ix_content_schedules_content_entry_id'), table_name='content_schedules')
    op.drop_table('content_schedules')
    # ### end Alembic commands ###
