"""add_content_relationships_table

Revision ID: 69c20a9ee9a7
Revises: 3a3ceb7b647d
Create Date: 2025-11-24 21:14:39.163437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c20a9ee9a7'
down_revision: Union[str, Sequence[str], None] = '3a3ceb7b647d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_relationships',
    sa.Column('source_entry_id', sa.Integer(), nullable=False),
    sa.Column('target_entry_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_entry_id'], ['content_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entry_id'], ['content_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entry_id', 'target_entry_id', 'relationship_type', name='uq_content_relationship')
    )
    op.create_index(op.f('ix_content_relationships_id'), 'content_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_content_relationships_relationship_type'), 'content_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_content_relationships_source_entry_id'), 'content_relationships', ['source_entry_id'], unique=False)
    op.create_index(op.f('ix_content_relationships_target_entry_id'), 'content_relationships', ['target_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_relationships_target_entry_id'), table_name='content_relationships')
    op.drop_index(op.f('ix_content_relationships_source_entry_id'), table_name='content_relationships')
    op.drop_index(op.f('ix_content_relationships_relationship_type'), table_name='content_relationships')
    op.drop_index(op.f('ix_content_relationships_id'), table_name='content_relationships')
    op.drop_table('content_relationships')
    # ### end Alembic commands ###
