"""add_content_templates

Revision ID: c280720c9c41
Revises: 22ef6997daa0
Create Date: 2025-11-24 21:53:00.028819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c280720c9c41'
down_revision: Union[str, Sequence[str], None] = '22ef6997daa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('content_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('field_defaults', sa.JSON(), nullable=False),
    sa.Column('field_config', sa.JSON(), nullable=True),
    sa.Column('content_structure', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_templates_content_type_id'), 'content_templates', ['content_type_id'], unique=False)
    op.create_index(op.f('ix_content_templates_id'), 'content_templates', ['id'], unique=False)
    op.create_index(op.f('ix_content_templates_organization_id'), 'content_templates', ['organization_id'], unique=False)
    op.create_index('ix_template_published', 'content_templates', ['organization_id', 'content_type_id', 'is_published'], unique=False)
    op.create_index('uix_template_org_type_name', 'content_templates', ['organization_id', 'content_type_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_template_org_type_name', table_name='content_templates')
    op.drop_index('ix_template_published', table_name='content_templates')
    op.drop_index(op.f('ix_content_templates_organization_id'), table_name='content_templates')
    op.drop_index(op.f('ix_content_templates_id'), table_name='content_templates')
    op.drop_index(op.f('ix_content_templates_content_type_id'), table_name='content_templates')
    op.drop_table('content_templates')
    # ### end Alembic commands ###
